baseURL = "https://rmalstrom.github.io/"
title = "Ricky Malstrom"
# Remove this if you’re using modules:
# theme = "terminal"

[module]
  [[module.imports]]
    path = "github.com/panr/hugo-theme-terminal/v4"

# Optional but helps on Pages if you still get missing CSS:
# relativeURLs = true
# canonifyURLs = true

[pagination]
  pagerSize = 10

theme = "Terminal"   # important

[markup.highlight]
  noClasses = false   # required so the theme's Chroma styles apply


[params]
  description = "Engineer • Maker • Problem Solver"
  themeColor = "blue"   # green, blue, red, orange, pink
  # fullWidthTheme = true
  contentTypeName = "posts"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 2

  [module]
  [[module.imports]]
    path = "github.com/panr/hugo-theme-terminal/v4"

