# ----------------------------
# Basic site settings
# ----------------------------
baseURL = "https://rmalstrom.github.io/"
title = "Ricky Malstrom"
languageCode = "en-us"

[pagination]
  pagerSize = 10

enableRobotsTXT = true

# ----------------------------
# Use the Terminal theme via Hugo Modules
# (Do NOT also set `theme = "terminal"`)
# ----------------------------
[module]
  [[module.imports]]
    path = "github.com/panr/hugo-theme-terminal/v4"

# ----------------------------
# Theme params (safe defaults)
# ----------------------------
[params]
  # These are Terminal theme options; adjust later if you want
  centerTheme = true
  showMenuItems = 5
  # choose one of: "orange", "blue", "red", "green", "pink", "yellow"
  themeColor = "blue"

# If your menu is empty, this block can be omitted.
# Keeping it blank is harmless and valid TOML.
[menu]
