baseURL = "https://<your-username>.github.io/"   # or ".../<repo>/" for project pages
languageCode = "en-us"
title = "My Portfolio"
paginate = 10

theme = "terminal"   # <— use this when the theme is inside /themes

[params]
  description = "Engineer • Maker • Problem Solver"
  themeColor = "green"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 2
