# ----------------------------
# Basic site settings
# ----------------------------
baseURL = "https://rmalstrom.github.io/"
title = "Ricky Malstrom"
languageCode = "en-us"

[pagination]
  pagerSize = 10

enableRobotsTXT = true

# ----------------------------
# Use the Terminal theme via Hugo Modules
# (Do NOT also set `theme = "terminal"`)
# ----------------------------
[module]
  [[module.imports]]
    path = "github.com/panr/hugo-theme-terminal/v4"

# ----------------------------
# Theme params (safe defaults)
# ----------------------------
[params]
  # These are Terminal theme options; adjust later if you want
  centerTheme = true
  showMenuItems = 5
  # choose one of: "blue", "red", "green", "pink", "yellow"
  themeColor = "blue"
  subtitle = "Mechatronics student • 3D printing nerd • Maker"

# If your menu is empty, this block can be omitted.
# Keeping it blank is harmless and valid TOML.
[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 3

  [[menu.main]]
    name = "Contact"
    url = "/about/#contact"
    weight = 4
