baseURL = "https://RMalstrom.github.io/"
languageCode = "en-us"
title = "My Portfolio"
paginate = 10

[params]
  description = "Engineer • Maker • Problem Solver"
  themeColor = "green"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 2

[module]
  [[module.imports]]
    path = "github.com/panr/hugo-theme-terminal/v4"
