name: Deploy Hugo site to Pages

  

on:
  push:
    branches: [ "main" ]   # change to "master" if that's your default branch
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Setup Go (for Hugo Modules)
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.151.2'
          extended: true

      # This line creates/updates go.sum based on your config/module imports
      - name: Resolve Hugo Modules
        run: |
          hugo mod get -u ./...
          hugo mod tidy


      - name: Build
        run: hugo --cleanDestinationDir --minify

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
  
